import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./_sections/sidebar";
import Providers from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body className={inter.className}>
        <Providers>
          <div className=" flex flex-col xl:flex-row overflow-hidden">
            <Sidebar />
            <div className=" flex-1 bg-slate-200"> {children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
